Repository YituHealthcare/Arc, pull requests merged in 2020-12, with the labels that each got.

#36 Feature/exception handler
  graphql/src/main/java/ai/care/arc/graphql/exception/CustomDataFetcherExceptionHandler.java
  graphql/src/test/java/ai/care/arc/graphql/exception/CustomDataFetcherExceptionHandlerTest.java
Labels: enhancement

#30 GraphqlClient
  graphql-client/README.md
  graphql-client/pom.xml
  graphql-client/src/main/java/ai/care/arc/graphqlclient/GraphqlClientFactoryBean.java
  graphql-client/src/main/java/ai/care/arc/graphqlclient/GraphqlClientInvocationHandler.java
  graphql-client/src/main/java/ai/care/arc/graphqlclient/GraphqlClientScanner.java
  graphql-client/src/main/java/ai/care/arc/graphqlclient/GraphqlClientsRegistrar.java
  graphql-client/src/main/java/ai/care/arc/graphqlclient/GraphqlTemplate.java
  graphql-client/src/main/java/ai/care/arc/graphqlclient/annotation/EnableGraphqlClients.java
  graphql-client/src/main/java/ai/care/arc/graphqlclient/annotation/GraphqlClient.java
  graphql-client/src/main/java/ai/care/arc/graphqlclient/annotation/GraphqlMapping.java
  graphql-client/src/main/java/ai/care/arc/graphqlclient/annotation/GraphqlParam.java
  graphql-client/src/main/java/ai/care/arc/graphqlclient/exception/GraphqlClientException.java
  graphql-client/src/main/java/ai/care/arc/graphqlclient/model/GraphqlError.java
  graphql-client/src/main/java/ai/care/arc/graphqlclient/model/GraphqlRequest.java
  graphql-client/src/main/java/ai/care/arc/graphqlclient/model/GraphqlResponse.java
  graphql-client/src/main/java/ai/care/arc/graphqlclient/model/SourceLocation.java
  graphql-client/src/test/java/ai/care/arc/graphqlclient/GraphqlClientInvocationHandlerTest.java
  graphql-client/src/test/java/ai/care/arc/graphqlclient/GraphqlClientScannerTest.java
  graphql-client/src/test/java/ai/care/arc/graphqlclient/GraphqlClientsRegistrarTest.java
  graphql-client/src/test/java/ai/care/arc/graphqlclient/GraphqlTemplateTest.java
  graphql-client/src/test/java/ai/care/arc/graphqlclient/mock/MockResponseData.java
  graphql-client/src/test/java/ai/care/arc/graphqlclient/mock/correct/MockGraphqlClient.java
  graphql-client/src/test/java/ai/care/arc/graphqlclient/mock/interfaceonly/MockGraphqlClient.java
  graphql-client/src/test/java/ai/care/arc/graphqlclient/mock/urlempty/MockGraphqlClient.java
  graphql-client/src/test/resources/echo.graphql
  graphql/src/main/java/ai/care/arc/graphql/GraphqlAutoConfiguration.java
  graphql/src/main/java/ai/care/arc/graphql/client/GraphqlClient.java
  graphql/src/test/java/ai/care/arc/graphql/GraphqlAutoConfigurationTest.java
  graphql/src/test/java/ai/care/arc/graphql/client/GraphqlClientTest.java
  pom.xml
  sample/graphql-client-sample/README.md
  sample/graphql-client-sample/pom.xml
  sample/graphql-client-sample/src/main/java/ai/care/arcgraphqlclientsample/ArcGraphqlClientSampleApplication.java
  sample/graphql-client-sample/src/main/resources/ql/echo.graphql
Labels: enhancement

#39 bugfix: 项目中使用@EnableFeignClients后Graphql方法注册失败，无法调用
  graphql/src/main/java/ai/care/arc/graphql/GraphQLProvider.java
Labels: bug

#41 break up drop and create schema
  dgraph/src/main/java/ai/care/arc/dgraph/datasource/DataSourceInitializer.java
  dgraph/src/main/resources/META-INF/additional-spring-configuration-metadata.json
  dgraph/src/test/java/ai/care/arc/dgraph/datasource/DataSourceInitializerTest.java
Labels: bug

#37 fix unionClassHandle for list
  dgraph/src/main/java/ai/care/arc/dgraph/repository/parser/DgraphParser.java
Labels: bug

#35 fix getOne and add DgraphSQLHelperTest
  dgraph/src/main/java/ai/care/arc/dgraph/repository/SimpleDgraphRepository.java
  dgraph/src/main/java/ai/care/arc/dgraph/util/DgraphSQLHelper.java
  dgraph/src/main/java/ai/care/arc/dgraph/util/DgraphSqlHelper.java
  dgraph/src/test/java/ai/care/arc/dgraph/util/DgraphSqlHelperTest.java
Labels: bug

#50 fix generated code format
  generator/src/main/java/com/github/yituhealthcare/arc/generator/codegen/TypeGenerator.java
  generator/src/main/java/com/github/yituhealthcare/arc/generator/codegen/util/JavadocUtils.java
  generator/src/main/java/com/github/yituhealthcare/arc/generator/io/CodeWriter.java
  generator/src/test/java/com/github/yituhealthcare/arc/generator/codegen/util/JavadocUtilsTest.java
  generator/src/test/java/com/github/yituhealthcare/arc/generator/io/CodeWriterTest.java
  generator/src/test/resources/type_test_Mutation.java
  generator/src/test/resources/type_test_Project.java
  generator/src/test/resources/type_test_Query.java
Labels: bug

#52 Arc Maven Plugin
  README.md
  generator/src/main/java/com/github/yituhealthcare/arc/generator/JavaCodeGenerator.java
  generator/src/main/java/com/github/yituhealthcare/arc/generator/conf/CodeGenConfig.java
  generator/src/main/java/com/github/yituhealthcare/arc/generator/conf/CodeGenConfigHandler.java
  generator/src/test/java/com/github/yituhealthcare/arc/generator/conf/CodeGenConfigHandlerTest.java
  generator/src/test/java/com/github/yituhealthcare/arc/generator/conf/CodeGenConfigTest.java
  maven-plugin/README.md
  maven-plugin/pom.xml
  maven-plugin/src/main/java/com/github/yituhealthcare/arc/mavenplugin/GeneratorAliasMojo.java
  maven-plugin/src/main/java/com/github/yituhealthcare/arc/mavenplugin/GeneratorMojo.java
  maven-plugin/src/test/java/com/github/yituhealthcare/arc/mavenplugin/GeneratorAliasMojoTest.java
  maven-plugin/src/test/java/com/github/yituhealthcare/arc/mavenplugin/GeneratorMojoTest.java
  maven-plugin/src/test/resources/test_config.json
  maven-plugin/src/test/resources/test_error_config
  pom.xml
  sample/generator-sample/README.md
  sample/generator-sample/pom.xml
  sample/generator-sample/src/main/resources/application-default.properties
  sample/generator-sample/src/main/resources/arc-generator.json
  sample/generator-sample/src/main/resources/graphql/schema.graphqls
Labels: enhancement, generator

#55 Generate Json to Map
  core/src/main/java/com/github/yituhealthcare/arc/core/common/GraphqlFieldType2JavaTypeConverter.java
  generator/src/main/java/com/github/yituhealthcare/arc/generator/convert/GraphqlType2JavapoetTypeName.java
  generator/src/main/java/com/github/yituhealthcare/arc/generator/dictionary/GeneratorGlobalConst.java
  generator/src/main/java/com/github/yituhealthcare/arc/generator/io/CodeWriter.java
  generator/src/test/resources/type_interface_test.graphqls
  generator/src/test/resources/type_interface_test_Project.java
Labels: bug, generator

#58 set accept json only
  graphql-client/src/main/java/com/github/yituhealthcare/arc/graphqlclient/GraphqlTemplate.java
Labels: bug

#60 根据泛型反序列化 Graphql response
  graphql-client/src/main/java/com/github/yituhealthcare/arc/graphqlclient/GraphqlClientInvocationHandler.java
  graphql-client/src/main/java/com/github/yituhealthcare/arc/graphqlclient/GraphqlTemplate.java
  graphql-client/src/main/java/com/github/yituhealthcare/arc/graphqlclient/model/GraphqlResponse.java
  graphql-client/src/test/java/com/github/yituhealthcare/arc/graphqlclient/GraphqlClientInvocationHandlerTest.java
  graphql-client/src/test/java/com/github/yituhealthcare/arc/graphqlclient/GraphqlTemplateTest.java
  sample/graphql-client-sample/src/main/java/com/github/yituhealthcare/arcgraphqlclientsample/ArcGraphqlClientSampleApplication.java
Labels: enhancement

#62 代码生成器修改graphqlMethod判断规则
  generator/src/main/java/com/github/yituhealthcare/arc/generator/codegen/ApiGenerator.java
  generator/src/main/java/com/github/yituhealthcare/arc/generator/codegen/RepositoryGenerator.java
  generator/src/main/java/com/github/yituhealthcare/arc/generator/codegen/TypeGenerator.java
  generator/src/main/java/com/github/yituhealthcare/arc/generator/convert/IsContainsGraphqlMethodField.java
  generator/src/main/java/com/github/yituhealthcare/arc/generator/convert/IsGraphqlMethodField.java
  generator/src/test/java/com/github/yituhealthcare/arc/generator/codegen/GeneratorIntegralTest.java
  generator/src/test/resources/api_test.graphqls
  generator/src/test/resources/type_test.graphqls
  generator/src/test/resources/type_test_Project.java
Labels: bug, generator

#63 生成代码重命名
  dgraph/src/main/java/com/github/yituhealthcare/arc/dgraph/dictionary/IDomainClass.java
  generator/src/main/java/com/github/yituhealthcare/arc/generator/JavaCodeGenerator.java
  generator/src/main/java/com/github/yituhealthcare/arc/generator/codegen/DataFetcherGenerator.java
  generator/src/main/java/com/github/yituhealthcare/arc/generator/codegen/TypeGenerator.java
  generator/src/main/java/com/github/yituhealthcare/arc/generator/codegen/util/PackageManager.java
  generator/src/main/java/com/github/yituhealthcare/arc/generator/conf/CodeGenType.java
  generator/src/main/java/com/github/yituhealthcare/arc/generator/dictionary/GeneratorGlobalConst.java
  generator/src/test/java/com/github/yituhealthcare/arc/generator/JavaCodeGeneratorTest.java
  generator/src/test/java/com/github/yituhealthcare/arc/generator/codegen/GeneratorIntegralTest.java
  generator/src/test/resources/api_test_QueryService.java
  generator/src/test/resources/data_fetcher_test.graphqls
  generator/src/test/resources/data_fetcher_test_MutationDataFetcher.java
  generator/src/test/resources/data_fetcher_test_ProjectDataFetcher.java
  generator/src/test/resources/data_fetcher_test_QueryDataFetcher.java
  generator/src/test/resources/dictionary_test_E1.java
  generator/src/test/resources/dictionary_test_ProjectRepository.java
  generator/src/test/resources/input_test_I1.java
  generator/src/test/resources/java_code_generator_schema.graphqls
  generator/src/test/resources/repository_test_ProjectRepository.java
  generator/src/test/resources/type_interface_test_Entity.java
  generator/src/test/resources/type_interface_test_Milestone.java
  generator/src/test/resources/type_interface_test_Project.java
  generator/src/test/resources/type_test_Milestone.java
  generator/src/test/resources/type_test_Mutation.java
  generator/src/test/resources/type_test_Project.java
  generator/src/test/resources/type_test_Query.java
  generator/src/test/resources/type_test_User.java
  generator/src/test/resources/type_union_test_Entity.java
  generator/src/test/resources/type_union_test_Milestone.java
  generator/src/test/resources/type_union_test_Project.java
Labels: enhancement, generator

#64 代码生成时type model 提供builder模式
  generator/src/main/java/com/github/yituhealthcare/arc/generator/codegen/TypeGenerator.java
  generator/src/main/java/com/github/yituhealthcare/arc/generator/codegen/spec/TypeSpecGenBuilder.java
  generator/src/test/java/com/github/yituhealthcare/arc/generator/codegen/spec/TypeSpecGenBuilderTest.java
  generator/src/test/resources/type_interface_test_Milestone.java
  generator/src/test/resources/type_interface_test_Project.java
  generator/src/test/resources/type_test_Milestone.java
  generator/src/test/resources/type_test_Project.java
  generator/src/test/resources/type_test_User.java
  generator/src/test/resources/type_union_test_Milestone.java
  generator/src/test/resources/type_union_test_Project.java
Labels: enhancement, generator

#66 GraphqlMethod同时生成field & setter & getter
  CHANGELOG.md
  generator/src/main/java/com/github/yituhealthcare/arc/generator/codegen/TypeGenerator.java
  generator/src/test/resources/type_test_Project.java
Labels: enhancement, generator

#70 增加graphql validation 扩展依赖
  graphql/pom.xml
  graphql/src/main/java/com/github/yituhealthcare/arc/graphql/support/RuntimeWiringRegistry.java
  pom.xml
  sample/graphql-sample/src/main/resources/graphql/schema.graphqls
Labels: enhancement
